version: '3.8'

services:
  quest1-api:
    build: .
    container_name: quest1_detection_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./artifacts:/app/artifacts
    restart: unless-stopped